create database bank;
use bank;

-- Create AdminTable
CREATE TABLE AdminTable (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    admin_password VARCHAR2(100) NOT NULL,
    admin_name VARCHAR2(100),
    date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert into AdminTable
INSERT INTO AdminTable (username, admin_password, admin_name)
VALUES ('adminuser', 'adminpassword123', 'siva');

-- Create Staff Table
CREATE TABLE Staff (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    staff_name VARCHAR2(100),
    position VARCHAR2(100),
    email VARCHAR2(100),
    phone VARCHAR2(15),
    date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO Staff (username, password, staff_name, position, email, phone)
VALUES 
('staffuser1', 'staffpassword123', 'prasath', 'Manager', 'prasath@gmail.com', '123-456-7890'),
('staffuser2', 'staffpassword456', 'viswa', 'Teller', 'viswa@gmail.com', '987-654-3210'),
('staffuser3', 'staffpassword789', 'kumar', 'Clerk', 'kumar@mail.com', '111-222-3333'),
('staffuser4', 'staffpassword321', 'santosh', 'Loan Officer', 'santosh@gmail.com', '444-555-6666'),
('staffuser5', 'staffpassword654', 'rahul', 'Customer Service', 'rahul@mail.com', '777-888-9999');


CREATE TABLE Client (
    client_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR2(100),
    email VARCHAR2(100) NOT NULL UNIQUE,
    phone VARCHAR2(15),
    address VARCHAR2(255),
    date_of_birth DATE,
    date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO Client (client_name, email, phone, address, date_of_birth)
VALUES
('bala', 'bala@gmil.com', '555-123-4567', '1725 Slough Ave, Scranton, PA', TO_DATE('1970-03-15', 'YYYY-MM-DD'));
('sriram', 'sriram@gmail.com', '555-987-6543', '220 Bear Creek Rd, Scranton, PA', TO_DATE('1975-01-20', 'YYYY-MM-DD'));
('prem', 'prem@gmail.com', '555-654-3210', '1 Scranton Business Park, Scranton, PA', TO_DATE('1980-10-01', 'YYYY-MM-DD'));
('muthu', 'muthu@gmail.com', '555-111-2233', '2 Scranton Business Park, Scranton, PA', TO_DATE('1982-03-23', 'YYYY-MM-DD'));
('rayan', 'rayan@gmail.com', '555-432-8765', '3 Scranton Business Park, Scranton, PA', TO_DATE('1984-09-22', 'YYYY-MM-DD'));
('rio', 'rio@gmail.com', '555-222-4444', '4 Scranton Business Park, Scranton, PA', TO_DATE('1950-02-15', 'YYYY-MM-DD'));
('raja', 'raja@gmail.com', '555-555-6666', '5 Scranton Business Park, Scranton, PA', TO_DATE('1972-11-25', 'YYYY-MM-DD'));
('gokul', 'gokul@gmail.com', '555-777-8888', '6 Scranton Business Park, Scranton, PA', TO_DATE('1973-05-12', 'YYYY-MM-DD'));
('ram', 'ram@gmail.com', '555-888-9999', '7 Scranton Business Park, Scranton, PA', TO_DATE('1972-07-04', 'YYYY-MM-DD'));
('kumar', 'kumar@gmail.com', '555-999-0000', '8 Scranton Business Park, Scranton, PA', TO_DATE('1970-04-01', 'YYYY-MM-DD'));


CREATE TABLE Account (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id NUMBER,
    account_type VARCHAR2(50),
    balance NUMBER(15, 2) DEFAULT 0.00,
    date_opened TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_client FOREIGN KEY (client_id) REFERENCES Client(client_id) ON DELETE CASCADE
);


INSERT INTO Account (client_id, account_type, balance)
VALUES
(1, 'Savings', 1500.00),
(2, 'Savings', 2000.00),
(3, 'Savings', 2500.00),
(4, 'Savings', 3000.00),
(5, 'Savings', 3500.00),
(6, 'Savings', 4000.00),
(7, 'Savings', 4500.00),
(8, 'Savings', 5000.00),
(9, 'Savings', 5500.00),
(10, 'Savings', 6000.00);



select * from admintable;
select * from staff;
select * from client;
select * from Account;

select client.client_name,account.balance from client
join account on account.account_id=client.client_id
where client.client_name='bala';

select c.client_name,c.date_joined 
from client c
where date_joined >=dateadd(year,-1,getdata());

select top 1 c.client_name,a,balance
from client c
join account a on c.client_id=a_client_id
order by a.balance desc;

update account
set balance=balance + 1000
where account_id=3;

update account
set balance=balance - 500
where accout_id=3 and balance>=500;



UPDATE Account
SET balance = balance + 1000  -- Deposit $1000
WHERE account_id = 1;  -- Account ID to deposit into


select c.client_id,c.client_name,a.balance
from client c
left join account a on c.client_id=a.client_id;

select * from client where date_joined>=dateadd(day,-7,getdate());  --MS SQL

select * from client where date_joined >=sysdate-7;  --ORACLE SQL

update client set address =' aa Business Park, aaa, PA' where client_id in (1,2);

select * from client where lower(address) like '%scranton%';

select * from client where lower(address) not like '%scranton%';

select * from client where date_joined = sysdate;

SELECT * 
FROM Client
WHERE TRUNC(date_joined) = TRUNC(SYSDATE); ----oracle sql 

SELECT * 
FROM Client
WHERE CAST(date_joined AS DATE) = CAST(GETDATE() AS DATE);  --- MS SQL

Find Clients Who Joined This Month

select * from client where month(date_joined)=month(getdate()) 
and year(date_joined)=year(getdate());                          -----MS SQL


select * from client where extract(month from date_joined)=extract(month from sysdate)
and extract(year from date_joined)=extract(year from sysdate);                             ----ORACLE SQL

Calculate the Age of Each Client
                                                           
select client_name , datediff(year,date_joined)as age from client;  ----MS SQL

SELECT client_name, 
       TRUNC(MONTHS_BETWEEN(SYSDATE, date_of_birth) / 12) AS age  -----Oracle sql
FROM Client;


Group Clients by Year They Joined


select year(date_joined) as year_joined, count(*)as client_count 
from client 
group by year(year_joined )                                          ------MS SQL
order by year_joined desc;

SELECT EXTRACT(YEAR FROM date_joined) AS year_joined, COUNT(*) AS client_count
FROM Client
GROUP BY EXTRACT(YEAR FROM date_joined)                                                -------Oracle sql
ORDER BY year_joined;
